### ISSUE TITLE
Unable to login to the demo

### ISSUE THREAD

**Issue by rowanfuchs** [alfio-event/alf.io#1022]
the homepage of alf.io invites us to try alf.io on https://demo.alf.io/authentication but it's impossible to login, no demo account is provided either.

**Comment by cbellone** [comment]
Hi,
in order to login to the demo instance, you have to enter:

- your email address
- a password of your choice

this will create a new user / organization and you'll be able to try alf.io

data is purged regularly, and we won't use your email address for any purpose.

For better privacy we suggest you use a disposable email address service, like https://www.guerrillamail.com/
