### ISSUE TITLE
Error 500 after trying demo login

### ISSUE THREAD

**Issue by PaulGoldschmidt** [alfio-event/alf.io#1054]
Hey everyone,

I experienced right after creating a [demo account](https://demo.alf.io/authentication) an Error 500, it seems like the user gets not correctly created - any other people with the same problem?

Kind regards,
Paul

**Comment by sophiastr** [comment]
I am having the same problem.
i want to deal with this issue.
I am interested in contributing to the project you are developing.
Do you still need help?
I'm a beginner but I will try really hard.

**Comment by cbellone** [comment]
Hi @sophiastr,

> I am interested in contributing to the project you are developing.

that's great!

> Do you still need help?

always. We need all the help we can get :)

> I'm a beginner but I will try really hard.

great!

for this particular task, I believe that we have an issue with the server itself (meaning the virtual machine where alf.io-demo is running) or the database. We have to check it ourselves because access to the server is restricted.

Anyway I would suggest you to follow the README [here](https://github.com/alfio-event/alf.io) and try to setup the development environment to run alf.io locally. 
If you need any help please open [a discussion](https://github.com/alfio-event/alf.io/discussions/categories/dev)

Once you're up and running with the dev environment and you've familiarized with the application we can find a task for you to solve. How does that sound?

Celestino

**Comment by cbellone** [comment]
this should be fixed now. As suspected we had some issues with the database. Thanks @PaulGoldschmidt for letting us know!

**Comment by sophiastr** [comment]
Hello, it sounds great. 
I am willing to try and work hard. More specifically, I'm looking for a project to work on intensively in the coming months. I have worked a lot in Java but not in such a popular project. The project was successfully installed.
![image](https://user-images.githubusercontent.com/72817947/160291103-4212e5ec-a1d6-4b04-9bc3-070901951d64.png)
I need a couple of days in order to see and understand the project.
Since I want to work on a project that I will be able to contribute, I want to know if there are many issues available to be resolved.
Thank you very much.
Sophia Sotiropoulou

**Comment by jm9151821** [comment]
There's no way to create a demo account anymore. 
<img width="706" alt="Authentication requested" src="https://user-images.githubusercontent.com/32444279/185812400-4f6ea676-e8d2-4310-98c8-e240f571378d.png">

I tried to login to see if that would fix it but nope.
"Unknown user or wrong password. Please try again."
