### ISSUE TITLE
Ticket Purchase Process Issue: Stuck at Contact Details Entry

### ISSUE THREAD

**Issue by justusweigmann** [alfio-event/alf.io#1285]
**Describe the bug**
When the user wants to purchase a ticket, they are only asked for their first name, last name, and email address. However, the system expects, as described below under Additional context, the user's address information in order to generate an invoice. Unfortunately, there is no configuration option to request this data.

**To Reproduce**
The following steps are executed:
1. The user selects their desired option from the available ticket categories and additional options.
2. The user is redirected from the "Ticket" section to the "Contact Details" input screen.
3. The customer fills in the available fields: First name, last name, email address.
4. The user clicks on "continue," but nothing happens, and no error message is displayed.

**Screenshots**
<img width="1091" alt="Bildschirmfoto 2023-10-07 um 13 43 32" src="https://github.com/alfio-event/alf.io/assets/95694564/36c16253-38b8-46a0-b084-bf0ff2f8825d">

**Desktop (please complete the following information):**
 - OS: MacOS, iPadOS and iOS
 - Browser: Brave, Safari

**Additional context**
Failed to load resource: the server responded with a status of 422 ()
{
    "value": false,
    "validationErrors": [
        {
            "fieldName": "billingAddressLine1",
            "code": "error.emptyField",
            "arguments": null
        },
        {
            "fieldName": "billingAddressZip",
            "code": "error.emptyField",
            "arguments": null
        },
        {
            "fieldName": "billingAddressCity",
            "code": "error.emptyField",
            "arguments": null
        },
        {
            "fieldName": "vatCountryCode",
            "code": "error.emptyField",
            "arguments": null
        }
    ],
    "errorCount": 4,
    "success": false,
    "warnings": []
}

**Comment by cbellone** [comment]
Hi @justusweigmann ,
thank you for using alf.io!

This looks like a configuration problem. 
My (wild) guess is that you've enabled the following option (under the "Invoice" section)

![image](https://github.com/alfio-event/alf.io/assets/3385346/86e08d32-310d-459f-9183-1c2f32192285)

but then the invoice configuration is not complete. I.e. one or more of these options are empty:

![image](https://github.com/alfio-event/alf.io/assets/3385346/45ad2057-80d0-4e1d-b3c1-185b65e3adc5)
(Invoice address and VAT NR are mandatory if you want to generate an invoice)

that's why the form is not showing any invoicing-related but the backend is expecting to receive invoicing information.

Can you please double check the configuration?

**Comment by justusweigmann** [comment]
Hey Celestino,

Thanks for the help. I forgot to save the config. After making the suggested changes, it worked perfectly fine. Thanks.
