### ISSUE TITLE
Iframe embed of reservation process not functional on desktop.

### ISSUE THREAD

**Issue by doug86i** [alfio-event/alf.io#1348]
**Describe the bug**
When embedding the reservation process with an iframe under Wordpress, the front page is displayed but the continue button doesn't function.

**To Reproduce**
Browse to https://goodvibrationssociety.com/test/
Select at least one ticket.
Click continue at the bottom

**Expected behavior**
Iframe moves to next step of booking process

**Desktop (please complete the following information):**
Not functional under:
 - OS: MacOS Chrome 123.0.6312.59
 - OS: MacOS safari 17.3
 - OS: Windows 11 Edge 122.0.2365.92

Weirdly the process works on safari for iPhone running IOS 17.3.1

Thanks to all!

**Comment by doug86i** [comment]
Thanks for the situation update! Apologies if it's well documented.

I'll spin up an M5 instance and give it a test.

Many thanks!

**Comment by cbellone** [comment]
This is an undocumented "beta" feature :)
We don't consider this feature "production ready", mostly because of the cookie issue, so we haven't created a proper documentation for it yet. Any help with that in the future would be highly appreciated 

Thank you for validating the potential fix on M5! Really appreciated!

**Comment by doug86i** [comment]
Hey! Sorry for the delay, reporting back.

I've tested the same setup using current v.2.0-M5-SNAPSHOT

Seems to work great!

Thanks!
