### ISSUE TITLE
Additional fields should be disabled if already requested in the event

### ISSUE THREAD

**Issue by yankedev** [alfio-event/alf.io#175]
When editing an event:
Adding an additional field: if the field is already present in the list, it should be disabled from selection

**Comment by Praitheesh** [comment]
I'm happy to work on this issue.
I suggest rather hide the field from list if already selected , It would be more appropriate to validate unique `Field name` and `Label`.  Because some time admin may need to add same field again and again then he/she wish to modify the `Field name` or `Label`. example for Mobile number / Home number / Fax number.
