### ISSUE TITLE
Some addresses are not accepted for events also if they should

### ISSUE THREAD

**Issue by yankedev** [alfio-event/alf.io#252]
When creating a new event, using address:

> Via Cantonale 2C, 
> 6928 Manno
> 

it works correctly.
If I add some information to find the building and the room using this address:

> Sala Primavera,
> SUPSI DTI,
> Centro Galleria 2,
> Via Cantonale 2C, 
> 6928 Manno

the event cannot be created because the address is not valid.
Could we split the visible address (to appear in the GUI and tickets) from the address used to lookup the map and the timezone?

**Comment by yankedev** [comment]
I have used the address that is now not working in an event I created in October 2016 and it was accepted correctly, I'm not sure if the service provider has now introduced some restriction or if somthing has been changed in alf.io

**Comment by cbellone** [comment]
See https://github.com/exteso/alf.io/issues/177

Il 5-gen-2017 2:46 PM, "yankedev" <notifications@github.com> ha scritto:

I have used the address that is now not working in an event I created in
October 2016 and it was accepted correctly, I'm not sure if the service
provider has now introduced some restriction or if somthing has been
changed in alf.io

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/exteso/alf.io/issues/252#issuecomment-270647245>, or mute
the thread
