### ISSUE TITLE
seat map is possible?

### ISSUE THREAD

**Issue by ArchGalileu** [alfio-event/alf.io#258]
We are preparing for our theater and to be accessible to others but missing seat map. Is it possible?

Best regards
ArchGalileu

**Comment by cbellone** [comment]
Hi @ArchGalileu,

no, we don't have any "seats map" yet.
It's in our roadmap, but it won't be implemented in the near future. 

We accept pull requests for new features, so if someone of your organization can implement it, we would be happy to receive a pull request from you.
Alternatively, you could sponsor the development of this feature so that we can develop it in the next 1-2 releases

Thanks,
Celestino

**Comment by ArchGalileu** [comment]
Hi @cbellone 

How can i sponsor? 

Best regards
ArchGalileu

**Comment by cbellone** [comment]
Hi @ArchGalileu 
please write me an email: celestino _at_ exteso _dot_ com

thank you!
