### ISSUE TITLE
Lack of feedback if a user is created with an already existing username

### ISSUE THREAD

**Issue by Paultrouver** [alfio-event/alf.io#267]
If I try to create a new user with a username that's already been used, there is no feedback - nothing happens when I press the 'save' button. There needs to be a pop-up, with 'Sorry, that username is not available', or similar.

**Comment by Praitheesh** [comment]
@cbellone what is your opinion by using [angular-growl-2](http://janstevens.github.io/angular-growl-2/) to display server side validation messages( even for field duplicate value error) ?

**Comment by cbellone** [comment]
@Praitheesh I like the idea! It would be great if you could do a POC, in order to evaluate the impact on the existing codebase. The less the better. 
FYI, we are planning to refactor/redesign completely the admin in v. 2.0, which we hope to release late 2017 / early 2018, so I wouldn't put too much effort in implementing this right now. 

What do you think?

**Comment by Praitheesh** [comment]
Sure. I have just add easy fixed #247 with  angular-growl-2.  Please have a look.

**Comment by cbellone** [comment]
:+1: it looks OK, very easy and it has almost no impact on the existing code. Thank you!
