### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by thursd4y** [alfio-event/alf.io#311]
Are you planning on writting a general documentation for alf.io?

**Comment by cbellone** [comment]
Hi @thursd4y,
yes, definitely. 

We'd love to have some general documentation (like "howtos", "tips & tricks", "new features" and so on)
It would be great (and very much appreciated) if you could help us with that!

Celestino

**Comment by ArthurDuckham** [comment]
@cbellone 

Is this something that would still be helpful? If so what would be best to start with?

**Comment by cbellone** [comment]
Hi @ArthurDuckham,

yes, help here would be really appreciated!

We are collecting some very simple tutorials [here](https://github.com/alfio-event/alf.io/tree/master/docs). They're markdown files, and the goal would be to build a website starting from this content.

> If so what would be best to start with?

It would be great if you could add some other step-by-step tutorial. 
I would suggest to start with a "first setup" tutorial, as ATM we don't have anything explaining how to configure alf.io after the first boot (send email, maps integration, and so on).

Please note that, since we are heavily modifying the design / styling of the application in 2.0-M2, it would be better if the tutorial were based on this version.
If you need any help and/or if you need access to our test system, just let me know.

If you have any questions, please start a thread on our [mailing list](https://groups.google.com/d/forum/alfio), so we can use it as reference for other people.

Thank you!! :)
