### ISSUE TITLE
New event failure: API has changed?

### ISSUE THREAD

**Issue by kivanov82** [alfio-event/alf.io#356]
Been new to alf.io, but when trying to create a new event I've faced an exception while calling getEvent() in services.js.
I see that API at the backend expects a param nota json.
Bug perhaps?

**Comment by cbellone** [comment]
hi @kivanov82 

thank you for your interest in alf.io!

I am not able to reproduce your issue. Could you please give me more details and/or the exact steps to reproduce it?

Thank you!

**Comment by kivanov82** [comment]
hi @cbellone ,
sure, here it is:
1. Creation of a new event calls getEvent() service (service.js line 56). Couldn't trace the reason though.
2. That service makes an API call to '_/admin/api/events/'+name+'.json_'
3. Looking at EventApiController there is no handler for the call above but there is one for _/events/{name}_ (line 169, no json!). Hence 404
4. Once I've dropped .json all works well
PS. I think same story would be with _'/admin/api/events/id/'+eventId+'.json'_

Hope it helps!

**Comment by cbellone** [comment]
Hi @kivanov82,

thanks for the details. I think I am starting to understand what's happening.

Sure, we can remove the .json suffix, because it's redundant and we don't really need it, but it should work anyway because it is ignored by Spring MVC while trying to resolve the path. 
So that shouldn't be _the_ cause of your issue. 

I am wondering now if the error could be related in any way to the event URL.
e.g. does **name** in _/admin/api/events/'+**name**+'.json'_ contain any special character? 

Could you please share the exact URL that alf.io is trying to call, as you see it in the browser?

thanks!
Celestino

**Comment by kivanov82** [comment]
Thanks Celestino, 
I gave it another try and it works. Perhaps was my local glitch with Spring version.
