### ISSUE TITLE
Removing attendees from a reservation doesn't update the invoice

### ISSUE THREAD

**Issue by salmar** [alfio-event/alf.io#410]
When an attendee is removed from a reservation (and refund is done), the invoice should be updated accordingly.

**Comment by cbellone** [comment]
Hi @salmar, thanks for opening this issue.

As per #407, starting from 1.14 alf.io will always update the invoice/receipt in case of PENDING reservation modifications.

We (@syjer and I) are not entirely sure that updating a confirmed (and paid) reservation should always trigger an update on the invoice, since in some countries this is forbidden. 
For example in Italy the invoice must remain the same, and you must issue a "Credit Note" for the refunded amount. 

So it's not "safe" to update the invoice as default behavior.

We were thinking of adding an extra checkbox "Update Invoice" to the "Remove Ticket" view:

![image](https://user-images.githubusercontent.com/3385346/38405694-6d0049d2-3971-11e8-8703-54305697d712.png)

and then to add a row in the invoice, stating that one ticket has been refunded, something like

`Refund ticket aa-bb-cc-dd                  -100.00 CHF`

wdyt?

**Comment by cbellone** [comment]
implementation can be considered done.
@mg-1999 could you please provide a translation for the following text?

```
This invoice has been updated after the cancellation of one or more tickets and the refund of {0}.
``` 
Thank you very much!

**Comment by mg-1999** [comment]
Translated text:
Dit factuur is geupdate na de annulering van een of meer tickets en de terugbetaling van {0}.
