### ISSUE TITLE
Dashboard Gross income is not updating correctly

### ISSUE THREAD

**Issue by stephanj** [alfio-event/alf.io#427]
**Describe the bug**
When creating test registrations and afterwards removing those, the Gross income value does not change.

**To Reproduce**
1. Register a ticket
2. View dashboard to see "Gross income" value
3. Now cancel the reservation
4. You'll notice that the Gross income value does not change

**Expected behavior**
The "Gross income" value should be reduced with the amount of the reservation that has been canceled.

**Screenshots**

![image](https://user-images.githubusercontent.com/179457/40116711-ca49a9d6-5914-11e8-8c87-f7ae0eb5a6d5.png)

**Desktop (please complete the following information):**
 - Version v.1.14.3-SNAPSHOT

**Comment by cbellone** [comment]
The bug was in the reservation cancellation process. 
Tickets with status "TO_BE_PAID" (on-site cash payment method) weren't taken into account and as a consequence we didn't update their status.

I've also added a "cleanup" job on startup, in order to revert existing tickets with status "TO_BE_PAID" linked to cancelled reservations. 
So after installing the modifications, you should have a gross income of 0 EUR.
