### ISSUE TITLE
Follow EU VAT Rules (for event in Belgium)

### ISSUE THREAD

**Issue by stephanj** [alfio-event/alf.io#432]
**Describe the bug**
The following EU VAT rules apply for Belgium (and probably other EU countries)

* B2B : Belgian customer :  VAT 21% 
* B2B : Customer in EU (not Belgium) : No VAT + message
* B2B : Outside EU : No VAT + message

* B2C : Always 21% VAT

The registration for a (Belgian / EU) event should follow this, which is currently not the case.

![image](https://user-images.githubusercontent.com/179457/40234276-8365151c-5aa6-11e8-81cf-0049aa6a31b1.png)

**Comment by cbellone** [comment]
Should be fixed now.
I have added an additional config option, in the "EU-Specific invoice settings" section

![image](https://user-images.githubusercontent.com/3385346/40271943-2bb68be8-5ba5-11e8-935d-1a895ee7f02a.png)

the default for this flag is true, for backward compatibility, so in order to comply with Belgian rules you have to set it to false
