### ISSUE TITLE
Make it clear which VAT Country code is used

### ISSUE THREAD

**Issue by stephanj** [alfio-event/alf.io#433]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/179457/40234546-8c89bfde-5aa7-11e8-9cb5-c5ae1768daf4.png)

It would be better to list also the VAT ISO Country code next to the full name.  That way it's clear for the user that they don't have to provide this in the text field.

**Describe the solution you'd like**

Show  ""BE - Belgium" instead of "Belgium".  Hinting to the user the BE prefix is already selected.

Full list for EU is 

```
    AT, //("AT", "AT - Austria"),
    BE, //("BE", "BE - Belgium"),
    BG, //("BG", "BG - Bulgaria"),
    HR, //("HR", "HR - Croatia"),
    CY, //("CY", "CY - Cyprus"),
    CZ, //("CZ", "CZ - Czech Republic"),
    DE, //("DE", "DE - Germany"),
    DK, //("DK", "DK - Denmark"),
    EE, //("EE", "EE - Estonia"),
    EL, //("EL", "EL - Greece"),
    ES, //("ES", "ES - Spain"),
    FI, //("FI", "FI - Finland"),
    FR, //("FR", "FR - France"),
    GB, //("GB", "GB - United Kingdom"),
    HU, //("HU", "HU - Hungary"),
    IE, //("IE", "IE - Ireland"),
    IT, //("IT", "IT - Italy"),
    LT, //("LT", "LT - Lithuania"),
    LU, //("LU", "LU - Luxembourg"),
    LV, //("LV", "LV - Latvia"),
    MT, //("MT", "MT - Malta"),
    NL, //("NL", "NL - The Netherlands"),
    PL, //("PL", "PL - Poland"),
    PT, //("PT", "PT - Portugal"),
    RO, //("RO", "RO - Romania"),
    SE, //("SE", "SE - Sweden"),
    SI, //("SI", "SI - Slovenia"),
    SK; //("SK", "SK - Slovakia");
```

**Comment by syjer** [comment]
taking care of it.

**Comment by stephanj** [comment]
The EU VIES web service only allows verification of EU country VAT numbers. 
Non EU VAT numbers can not be verified, as a result the "Validate VAT Nr." button should be hidden when a non EU country is selected.

**Comment by cbellone** [comment]
I agree, but the current implementation of the UI (1.x) does not allow that. We will improve this in v2.

For #432, in order to comply with Belgian rules, we have added the possibility to not apply VAT for NON-EU B2B Customers. 
The solution has been to use the same "vat validation" mechanism for doing that (see https://github.com/alfio-event/alf.io/blob/7b8f5bdbe679ebeab4a03dc3103770dce5cb1b55/src/main/java/alfio/manager/EuVatChecker.java#L72:L91): 

1. If the customer is a business entity based in the EU, we trigger the VIES validation, and then
   a. if the country of business of the customer is the same as the organizer, VAT is applied
   b. if the country of business of the customer is **not** the same as the organizer, VAT is not applied

2. If the customer is a business entity based outside of the EU, we skip validation (we consider VAT valid) and then
   a. if "Apply VAT for non EU B2B customers" is true (default), VAT is still applied
   b. if "Apply VAT for non EU B2B customers" is false (as in your case), VAT is not applied 

We still need a button on the payment page for triggering this mechanism. A good compromise would be to rename the button to "apply" if the selected country is outside of EU...

WDYT?

**Comment by cbellone** [comment]
implemented
