### ISSUE TITLE
Ticket Category selection not working?!

### ISSUE THREAD

**Issue by vorburger** [alfio-event/alf.io#522]
**Describe the bug**

On https://tickets.learn.study/event/scratchday-ch/ there are 3 categories of tickets, but unless I'm really really stupid and tired, it seems to me that one cannot actually select any of them - what am I missing?

It say "ND" on the right - what does that mean? There are free tickets (I've just created it) and I've published the event ... does one need to do anything else?

PS: If absolutely required, I'm even willing to create you an accout / share the admin password to debug it.. but hopefully it's something obvious.

**Comment by cbellone** [comment]
Hi @vorburger ,

I think this is related to #521. When you create an event, you can set a sale period for each Ticket Category. This make sense especially for paid events like conferences, where you usually buy "Blind Bird", "Early Bird", "Full Price" tickets. You can define the sale period by defining the category validity:

![image](https://user-images.githubusercontent.com/3385346/46317335-fc35fa00-c5d2-11e8-943d-840fca15d894.png)

that's why you can't buy a ticket now: the tickets will be on sale from 24.11

![image](https://user-images.githubusercontent.com/3385346/46317485-664e9f00-c5d3-11e8-9bea-28532c528b21.png)

If you want to set a validity date for the tickets (and not for the category), you can do that by editing the "Advanced Options" for the category:
![image](https://user-images.githubusercontent.com/3385346/46317558-b0378500-c5d3-11e8-93ad-7eec817396f4.png)

if you leave one field (from or to) blank, it will default to the corresponding event date (start, end respectively)

**Comment by vorburger** [comment]
close via https://github.com/alfio-event/alf.io-website/pull/5 ?
