### ISSUE TITLE
Make easier to print again the badge of an attendee who already checked in

### ISSUE THREAD

**Issue by raffaellar** [alfio-event/alf.io#540]
Please add the QR CODE button alongside the REVERT CHECK-IN button in the alf.io backoffice UI.
This way retrieving the qr code to scan it would be way faster than it is now.

**Comment by NassimBounouas** [comment]
Hi,
I just discovered this project today and I tried to pick an easy issue.

After some local testing and sources reading, I tried this modification and It seems to fit the issue needs : 

https://github.com/NassimBounouas/alf.io/commit/6096619442f7fbbc66afcb31d20bc112e5be2065

Can someone (@cbellone ?) confirm me that's enough to response to @raffaellar request because it's was really (too ?) easy , I'm afraid to missunderstand and to do a wrong PR containing only one line.

*Result preview :*

![al io_qrcode](https://user-images.githubusercontent.com/18635821/48748984-0e4e2380-ec79-11e8-9915-5110289ebc5c.png)

Thank you

**Comment by syjer** [comment]
hi @NassimBounouas , yes, the change is the correct one. Could you provide a pull request ? Thank you 👍

**Comment by NassimBounouas** [comment]
Hi @syjer, the PR is done (https://github.com/alfio-event/alf.io/pull/550).

**Comment by syjer** [comment]
implemented, will be released in the M1 version
