### ISSUE TITLE
No Docker images for recent releases

### ISSUE THREAD

**Issue by asymmetric** [alfio-event/alf.io#584]
I noticed that there are no Docker images for the last two minor releases (one of which is a seurity update). Would be great if they could be pushed (especially 1.16.3).

Is there an automated process in place for pushing new versions to DockerHub?

**Comment by cbellone** [comment]
You're absolutely right. Sorry for that. 
I've pushed the images, now you should be able to download them

> Is there an automated process in place for pushing new versions to DockerHub?
no, not at the moment. Are you interested in helping us building it? 

Thanks
Celestino

**Comment by asymmetric** [comment]
Sure, how can I help?

**Comment by cbellone** [comment]
Great, thanks!

I think the easiest way for this would be if you could set it up on a separate repo (under your namespace) so that we can fork from **alfio-event** org, but I am open to suggestions.

WDYT?

**Comment by syjer** [comment]
hi @asymmetric , the images are available https://hub.docker.com/r/alfio/alf.io/tags :) enjoy.

**Comment by vorburger** [comment]
just FTR https://github.com/alfio-event/alf.io/pull/628 adds a link to Docker Hub to the README.

@cbellone Just FYI, fully automating this, just so that you don't have to do it manually again in the future, should be fairly trivial and normally take you only a moment... as @asymmetric as documented in #594, typically just a few clicks to point to Git URL and where the Dockerfile is. If you want to invite him or me (vorburger) as collaborator to https://hub.docker.com/u/alfio then we can probably do it for you. (I've personally never done it on docker.com, but have done it recently on https://quay.io which is a similar alternative container registry for another project, and it's straightforward.)

An automated build (this issue) can probably be done before and separate from #594 (unless I'm missing something).
