### ISSUE TITLE
Flycheck problem with 1.16.3 on Docker 

### ISSUE THREAD

**Issue by asymmetric** [alfio-event/alf.io#587]
**Describe the bug**
Running the 1.16.3 with the same `docker-compose.yml` file as 1.16.1 crasehs with:

```
alfio_1  | Caused by: org.flywaydb.core.internal.dbsupport.FlywaySqlException:
alfio_1  | Unable to obtain Jdbc connection from DataSource
alfio_1  | ------------------------------------------------
alfio_1  | SQL State  : 08001
alfio_1  | Error Code : 0
alfio_1  | Message    : Invalid sslmode value: prefer
```

**To Reproduce**

* Run `docker-compose up` with [this file](https://gist.github.com/asymmetric/84cff430ed267b3ecebd659ab28a19d5#file-docker-compose-yml)

**Expected behavior**

No crash

**Comment by asymmetric** [comment]
Hmm, it seems like the crash could actually be related to this log line:

```
db_1     | 2019-01-22 16:44:58.813 UTC [1] FATAL:  could not write lock file "postmaster.pid": No space left on device
```

**Comment by asymmetric** [comment]
Yeah, bug confirmed, the `No space left on device` problem was unrelated.

**Comment by cbellone** [comment]
This is weird. 

sslmode=prefer is the default in PostgreSQL (see [doc](https://www.postgresql.org/docs/8.4/libpq-connect.html#LIBPQ-CONNECT-SSLMODE)). We're just stating the obvious here.

Anyway, can you try to add the following environment variable, just to verify if the problem is really the sslmode:
POSTGRES_ENV_USE_SSL: 'disable'

**Comment by DottoreTozzi** [comment]
Yes, this does the trick...

**Comment by vorburger** [comment]
> POSTGRES_ENV_USE_SSL: 'disable'

same here.. not with `docker-compose up` but while I'm trying a `docker run --rm -e "POSTGRES_PORT_5432_TCP_ADDR=otto.db.elephantsql.com" ... alfio/alf.io:1.16.3` with https://www.elephantsql.com ...

BTW https://www.elephantsql.com/docs/faq.html#Does_ElephantSQL_support_TLS_SSL suggests this:

> We do support TLS (SSL). In most clients it is easy to use TLS by adding `?ssl=true` to the connection URL. More information can be found here: [PostgreSQL JDBC Driver Chapter 4. Using SSL](https://jdbc.postgresql.org/documentation/94/ssl-client.html)

As far as I understand, I can't override the JDBC URL from the environment variables? 

> Yes, this does the trick...

Confirming, that's a valid workaround, but that's insecure, agreed? 

So perhaps this `?ssl=true` should be added in the source?

**Comment by cbellone** [comment]
> Yes, this does the trick...
ok but that was not intended as a workaround. :-)

@vorburger: ssl=true is not as fine grained as ssl_mode, at least not for the JDBC driver, see https://jdbc.postgresql.org/. So I think we should investigate in other directions

I think that the real issue here is the default postgres docker image config.

have you tried with ssl_mode=allow ? Does it work? (see [doc](https://www.postgresql.org/docs/8.4/libpq-connect.html#LIBPQ-CONNECT-SSLMODE))

another option would be to create a certificate and then configure it, see https://gist.github.com/mrw34/c97bb03ea1054afb551886ffc8b63c3b . I think that https://github.com/FiloSottile/mkcert can be of help here.

**Comment by cbellone** [comment]
closed for inactivity
