### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by archenroot** [alfio-event/alf.io#595]
Please accept me as contributor for translating solution into Czech language in POEditor project.

**Comment by archenroot** [comment]
While I created these 2 files in commit, still in global configuration page these are not visible....

**Comment by cbellone** [comment]
Hi @archenroot ,
thank you for the translation!
In order to see the new language in the configuration, you have to define it here:
https://github.com/alfio-event/alf.io/blob/master/src/main/java/alfio/model/ContentLanguage.java#L37L39

Additionally, I would suggest you to remove the leading space from the translations, e.g:
https://github.com/alfio-event/alf.io/pull/596/files#diff-906b15301517ebd5cf9bf30edc419f85R9
as we use localized messages also in text/plain emails

As soon as you update the ContentLanguage class in the PR, I'll merge it. Thanks!!!

**Comment by archenroot** [comment]
@cbellone - thx for response, will do the changes suggested and re-pull request
