### ISSUE TITLE
Temperamental Setup

### ISSUE THREAD

**Issue by edzdamangere** [alfio-event/alf.io#614]
I got Alf.io to work and had fun using it for a little while, then rebooted the machine and now I’m back to square one.

Now what happens is that I enter the web address - http://www.domain.com and it redirects to https://localhost:8443/ but I have no settings pointing it in that direction! And when it points there, my browser says unable to establish a secure connection to https://localhost:8443. It’s so bizzarre!

As a backstory, there was an issue with Let’s Encrypt so I couldn’t secure the site at the very beginning, but now the certificate has been moved over to the server, and webmin is working fine.

On another note, I think an adjustment to the manual install tutorial is needed. I’d be happy to help.

My server is an Ubuntu 16.04 instance with nginx, hosted by Vultr

**Comment by cbellone** [comment]
Hi, and thanks for using alf.io!

I think you're missing something in the proxy configuration.

Alf.io **requires** SSL  when run in production. 
A proxy terminating SSL connection must at least forward the `X-Forwarded-Proto`header.
see [@asymmetric's comment](https://github.com/alfio-event/alf.io/issues/363#issuecomment-427663812) and [@flexwie's tutorial](https://gist.github.com/flexwie/a8572e8e7ef06ae844925ec857fa3b5b)

I am closing this since it is not really an alf.io issue. If you have any more questions on this topic, please join our [Mailing List](https://groups.google.com/d/forum/alfio), there are a lot of helpful people there :)
