### ISSUE TITLE
switch from postgresql-embedded to otj-pg-embedded

### ISSUE THREAD

**Issue by syjer** [alfio-event/alf.io#630]
as https://github.com/yandex-qatools/postgresql-embedded is marked as no more maintained. 

new library is: https://github.com/opentable/otj-pg-embedded

**Comment by vorburger** [comment]
> new library is: https://github.com/opentable/otj-pg-embedded

I'm curious why https://github.com/opentable/otj-pg-embedded instead of https://www.testcontainers.org/modules/databases/postgres/ ?   

FYI I've used testcontainers.org for other things (to launch Selenium in https://github.com/vorburger/minecraft-storeys-maker as well as to [launch etcd in jetcd](https://github.com/etcd-io/jetcd#launcher)), and it's great.

https://github.com/yandex-qatools/postgresql-embedded says: _"Please be adviced that the main maintainer of this project has successfuly migrated to the use of Test Containers project. This is the best possible alternative nowadays."_ (but FYI https://github.com/yandex-qatools/postgresql-embedded/pull/163)

**Comment by syjer** [comment]
@vorburger because test-containers requires docker. 

As far as I know, it still require sudo  which is something I don't consider good (and the fact that it has a demon).

When they will switch to `runc` with the rootless mode (https://github.com/opencontainers/runc#rootless-containers) I will be more open about that.

Please correct me if I'm wrong, maybe in the meantime it has changed :)

**Comment by vorburger** [comment]
> When they will switch to runc with the rootless mode

perhaps you would like to open an issue proposing this to test-containers? :smile_cat: 

PS: I'm guessing you know about it already, but just in case, you probably like `podman` (incl. `buildah`).

**Comment by syjer** [comment]
@vorburger ah, good idea about `podman`, when I've got some time I'll give a try :)

**Comment by vorburger** [comment]
> test-containers seems to be really docker centric: it really expect the docker daemon

yeah, so `sudo dnf install podman-docker`, which installs a very cool docker compatible CLI, won't work.

**Comment by bsideup** [comment]
Testcontainers dev here :)

> edit: looking at the code from test-containers, it seems to be really docker centric: it really expect the docker daemon :D.

Yes, the library is Docker focused, but we do understand that for testing, root maybe too much, and are happy to see the rootless mode progressing in the upstream Docker.

Podman is a nice idea, but, for this use case, you would still need daemon, especially on Mac/Windows. Otherwise, the libraries will be implementing their own daemons, so it isn't that much better.
