### ISSUE TITLE
Cant choose language in admin area

### ISSUE THREAD

**Issue by mg-1999** [alfio-event/alf.io#81]

**Comment by cbellone** [comment]
Hi @mg-1999,
could you please give more details about that?

thank you

**Comment by mg-1999** [comment]
There is no option to select the language in the admin area, or I could not find it.

**Comment by cbellone** [comment]
Hi Matthijs,

The current state is:

- The admin tool "/admin" is in English and there is no way to see labels
and messages in other languages (however in the dashboard you can see the
labels in your browser's language, but that was a proof of concept).
Currently we don't see any advantage in implementing and maintaining a
multi-language admin.

- There is not yet a way to define which languages are supported by the
public website.
Currently you can select which languages are supported by a particular
event but you can't do the same "system-wide". This could lead to a poor
user experience in some cases and will be fixed in the next weeks.

Celestino
Il 11-ott-2015 12:35 PM, "Matthijs" <notifications@github.com> ha scritto:

**Comment by mg-1999** [comment]
But if you add `?lang=nl` to the url in the navigation bar it sets the current language to that language if there is an translation available. So why is there no button for that?

**Comment by cbellone** [comment]
Yes, you're right. But this would change only a few labels in the
dashboard. Therefore it could be misleading for most users.

The other labels are only in English (and cannot be translated since the
text has been written directly in the HTML.
We planned a complete redesign and refactoring  of the admin area, which is
planned for early/mid 2016.
Il 12-ott-2015 07:33 PM, "Matthijs" <notifications@github.com> ha scritto:

**Comment by mg-1999** [comment]
If you need any help translating it into dutch, just ping me and I will do what I can.

**Comment by cbellone** [comment]
Thank you, we'll definitely do that :-)
