### ISSUE TITLE
How to disable Dev mode and start in live mode?

### ISSUE THREAD

**Issue by headarrow** [alfio-event/alf.io#834]
How to disable Dev mode and start in live mode?
i followed this guide
https://gist.github.com/flexwie/a8572e8e7ef06ae844925ec857fa3b5b
in application.properties it says
spring.profiles.active=dev
when i remove that from properties the website start showing ERR_TOO_MANY_REDIRECTS
yes i tired with https and http both have same error
whats the name of live profile?
how to disabled that message it keeps on saying The is in the development mode?

**Comment by cbellone** [comment]
Hi @headarrow ,

thank you for using alf.io!

Please check https://github.com/alfio-event/alf.io/issues/363#issuecomment-427663812 . It looks like that you're not setting the following header: 

`X-Forwarded-proto`

Anyway, if you are looking for a pre-built solution, please check also our entry on [Digitalocean Marketplace](https://marketplace.digitalocean.com/apps/alf-io). 
You can easily run alf.io on one of their 5$/month droplets with just one click.

I am closing this because it's not an issue. If you have other questions, please head to our [mailing list](https://groups.google.com/d/forum/alfio)

Thanks!
