### ISSUE TITLE
Optionally require confirmation for new registrations

### ISSUE THREAD

**Issue by nealey** [alfio-event/alf.io#855]
**Is your feature request related to a problem? Please describe.**
When people enter an invalid, or wrong, email address, there's no way for them to cancel that ticket. This fills seating slots with duplicates and/or garbage registrations.

In addition, sometimes people register but for whatever reason don't get email. Then they complain that we didn't send out any communications before the event.

**Describe the solution you'd like**
I'd very much like it if we had the option, for an event, to keep registration in a "Pending" state until someone confirms their registration in a link.

**Describe alternatives you've considered**
I can't think of anything that would be less work than modifying alfio :)

**Additional context**
Thanks for your consideration!

**Comment by cbellone** [comment]
Hi @nealey,

thanks for your feature request. I've discussed it with @syjer. 
We understand the problem, but we fear that adding an extra confirmation step might not be the best approach, at least not in the short term.
This is because the tickets will be reserved anyway until the reservation expires, so most likely you'll end up having lots of pending reservations with wrong email addresses. 
This could be a problem especially if you have few available seats for the event.

A more pragmatic solution would be to implement an [extension](https://github.com/alfio-event/alf.io-extensions) for the RESERVATION_VALIDATION <sup>[1](#footnote1)</sup> event, so that you can validate the email address using an email validation API of your choice. 

WDYT?

<a name="footnote1">1</a>: Documentation for this event is currently missing, we'll add it as soon as possible

**Comment by nealey** [comment]
This seems feasible, provided I can make extensions queue outgoing email and call back to alfio asynchronously. The process as I envision it would be:

1. User requests ticket
2. Alfio does what it needs to create structures, then calls extension
3. Extension sends an email with a "validation" link including some sort of nonce, tells alfio to send text saying "please go click on the link in your email". Alfio is done with this HTTP request/session, for now.
4. User clicks link, taking them back to alfio, which then passes the request (and, critically, the nonce) to the extension
5. Extension tells alfio "go ahead and issue the ticket"
6. Alfio tells user whatever string it uses for "you are all set", updates data structures to issue ticket, sends confirmation email, etc.

Does this workflow fit in with the event and extension API?

**Comment by cbellone** [comment]
> Does this workflow fit in with the event and extension API?

I am afraid not. The extension API is designed to communicate with external services when something happens during the reservation process. 
At the moment they cannot delay the reservation nor display custom content on the reservation page.

The workflow I had in mind would be more like:

1. User request ticket
2. User enters the required information (contact data + ticket data), then clicks on "continue"
3. Alf.io calls the RESERVATION_VALIDATION extension, if any. RESERVATION_VALIDATION is a synchronous event for which Alf.io expects to receive a result. 
4. The extension calls the email validation service, such as [sendgrid's](https://sendgrid.com/solutions/email-validation-api/), or [zerobounce's](https://www.zerobounce.net/email-validation-api.html) - or others
5. The extension returns the validation result
6. If the validation is not successful, the user is not allowed to proceed with the reservation

This way we can make sure that the email address entered by the user is correct, and at the same time we don't complicate the process by adding another step

would that solve your issue?

**Comment by nealey** [comment]
My employer won't allow 3rd party hosted services, which is why we're using Alfio and not something like cvent or eventbrite. So unfortunately, this clever solution isn't something we can implement.

Since email is inherently asynchronous, it sounds like this workflow just isn't going to mesh with Alfio. Would be possible to use some other hook to provide a "well check" URL, and set some sort of boolean `is_valid_email` flag on a ticket once the URL is clicked? Then we could modify the registration email to say "your registration is not complete until you click on the following URL: https://our.site/alfio/wellcheck?id=${ticket_id}".

**Comment by cbellone** [comment]
> My employer won't allow 3rd party hosted services, which is why we're using Alfio and not something like cvent or eventbrite. So unfortunately, this clever solution isn't something we can implement.
> 
data ownership is of paramount importance. This is why we've developed alf.io in the first place. 
I agree with your employer :100: 

Additionally, Alf.io has more features compared to eventbrite

> Since email is inherently asynchronous, it sounds like this workflow just isn't going to mesh with Alfio. Would be possible to use some other hook to provide a "well check" URL, and set some sort of boolean `is_valid_email` flag on a ticket once the URL is clicked? Then we could modify the registration email to say "your registration is not complete until you click on the following URL: [https://our.site/alfio/wellcheck?id=${ticket_id}](https://our.site/alfio/wellcheck?id=$%7Bticket_id%7D)".

I am afraid this can't be done because it's too specific to your use case. 

But I think that, with little modifications (see steps 4 and 5), the previous suggested workflow might work:

1. User request ticket
2. User enters the required information (contact data + ticket data), then clicks on "continue"
3. Alf.io calls the RESERVATION_VALIDATION extension, if any. RESERVATION_VALIDATION is a synchronous event for which Alf.io expects to receive a result. 
4. The extension calls **your** "email-validator" service
5. email-validator service checks if the email has already been validated. **If not**:
a. sends an e-mail with the validation link
b. returns an error because the e-mail address is not yet valid
c. (asynchronous) the user clicks on the validation link; email-validator service flags the email address as valid. After that, the user will be able to register
6. The extension returns the validation result
7. If the validation is not successful, the user is not allowed to proceed with the reservation


how does it sound?

P.S.: if you need help with integrating Alf.io with your tools/processes, please have a look at [Swicket](https://swicket.io) enterprise plan
