### ISSUE TITLE
question

### ISSUE THREAD

**Issue by baccinelli** [alfio-event/alf.io#890]
Hello, and really thanks for the great job made with alf.io. It' amazing..

I'm trying to configure paypal in demo mode but it stills not working
This is what I've done:
In payPal developer console with business account (how bad is it??... unbelievable)
- SandBox/Accounts -> new business account
- SandBox/Accounts -> new personal account
- My Apps & Credentials/new app -> ClientID + sercret (associated with previous business account)

In alf.io Organization settengs:
- Organizztion/Settings/payments/paypal -> Paypal REST API client ID = ClientID (paypal)
- Organizztion/Settings/payments/paypal -> Paypal REST API client secret = sercret (paypal)
- Organizztion/Settings/payments/paypal -> Paypal demo mode username 
![image](https://user-images.githubusercontent.com/59366136/79073290-0f587880-7ce6-11ea-947a-db53a1a336c1.png)
- Organizztion/Settings/payments/paypal -> Paypal demo mode password
![image](https://user-images.githubusercontent.com/59366136/79073320-2f883780-7ce6-11ea-9074-d000110c720b.png)

Then I set paypal payments in this way
![image](https://user-images.githubusercontent.com/59366136/79073353-5e9ea900-7ce6-11ea-9eed-cbea86e55aa6.png)

Making a new event and trying to pay it with paypal I'm getting this error:
![image](https://user-images.githubusercontent.com/59366136/79073399-9a397300-7ce6-11ea-86b4-b4542c8cb3c9.png)

I can't find any log in the server...

What could be wrong in my config?

Thanks in advance

**Comment by cbellone** [comment]
Hi @baccinelli ,

thank you for using alf.io!

I see two issues here:

1) you need to configure a REST API app, and then use the Client ID and Client secret (either sandbox or live)
see https://www.paypal.com/us/smarthelp/article/how-do-i-create-rest-api-credentials-ts1949
**please ignore** the demo username and password fields, since they are intended for the "demo" mode we use on https://demo.alf.io/admin/
We know that this is a bit confusing. We'll clarify things in the new version of the backoffice (currently WIP)

2) This error could be related to a bug on our side:
![image](https://user-images.githubusercontent.com/59366136/79073399-9a397300-7ce6-11ea-86b4-b4542c8cb3c9.png)
We have recently identified an resolved the bug, and we'll release a new version of alf.io probably this week. Do you have the possibility to build and test the current state of the [2.0-M2-maintenance](https://github.com/alfio-event/alf.io/tree/2.0-M2-maintenance) branch?
If not, please let me know and I'll share a pre-built binary
