### ISSUE TITLE
Restrict Sponsor Scans for specific API tokens

### ISSUE THREAD

**Issue by ebartz** [alfio-event/alf.io#931]
**Describe the bug**
When I create different Sponsor API tokens, every sponsor can see very scanned lead.

**To Reproduce**
Create an Event, and login with 2 different sponsor tokens. Each one sees the same sponsor scans.

**Expected behavior**
Every sponsor should only the leads that he scanned. Especially each sponsor should be able to take their own notes.

**Desktop (please complete the following information):**
 - OS: iOS

Actually I don't know if this is a bug. But our Events would have the ability to have multiple sponsors which individually take notes for their leads. I don't expect Sponsor A to see the scans and notes of Sponsor B.

**Comment by cbellone** [comment]
Hi @ebartz ,

API Keys for sponsors are meant to be company-wide. If you need to differentiate people within a company you need different API Keys.

Can you please describe more in detail the process, so that we can reproduce the bug? Are you using different phones or just one phone and different accounts?

Thanks!

**Comment by ebartz** [comment]
Hi @cbellone,

We have some events where we can have multiple Sponsors which all get the opportunity to scan their leads and take notes for themselves.

I would create an API token for each of those sponsors so that they can individually do things. In the Backend this also helps us to separate the scans and give everyone an export of their data.

In my test case I just created 2 Sponsor Keys and installed that on the same phone. In my Test I have scanned with Token-A and then switched on the same phone to Token-B and saw the previous scans. Just a few minutes ago I installed the same app on 2 different phones and have not seen the scans on both devices. Each just had the scans, that I created with the individual device.

So I guess my main problem was just that my test case did not involve separate devices.


---------

Seperate Question: I did not find the code of the app to check how it is actually submitting the scans. So I could not directly figure out which API gets called for that. Imagine I have Token-A and Token-B, is there any way that Token-A would get access to the scans of Token-B over the API, as both of the tokens have kinda the same permissions on an organization level?

Thanks :)

**Comment by cbellone** [comment]
> I would create an API token for each of those sponsors so that they can individually do things. In the Backend this also helps us to separate the scans and give everyone an export of their data.

exactly, that's how the feature has been designed to work

> In my test case I just created 2 Sponsor Keys and installed that on the same phone. In my Test I have scanned with Token-A and then switched on the same phone to Token-B and saw the previous scans. Just a few minutes ago I installed the same app on 2 different phones and have not seen the scans on both devices. Each just had the scans, that I created with the individual device.

this should not happen. I will try and see if I can reproduce the issue (should be something on the app, see below)
Anyway scans are not shared neither between devices nor on iCloud.

> 
> So I guess my main problem was just that my test case did not involve separate devices.

I will let you know as soon as I'm able to reproduce your error :-)

> 
> Seperate Question: I did not find the code of the app to check how it is actually submitting the scans. So I could not directly figure out which API gets called for that. Imagine I have Token-A and Token-B, is there any way that Token-A would get access to the scans of Token-B over the API, as both of the tokens have kinda the same permissions on an organization level?
> 

no, this should not happen, see: https://github.com/alfio-event/alf.io/blob/694a97489f0a9aada0629e8b336a0359e0e96f49/src/main/java/alfio/repository/SponsorScanRepository.java#L39
Each record is linked to the user (each API Key is actually a limited user with a random password), so another user of the same organization should not be able to retrieve scans from other users, unless they share the same API Key. 

In that case, if you have the following:

- Phone A and Phone B authenticated using the same API Key
- Phone A and Phone B scan the same badge (important!)
- Phone A writes some notes

then you would be able to see the notes also on Phone B after scanning another (or again the same) badge

anyway, since you're mentioning it, the code of the app itself is in a separate repository: 

https://github.com/alfio-event/Alf.ioBackoffice/blob/master/src/app/shared/scan/sponsor-scan.service.ts#L87

and this is the endpoint on the server:

https://github.com/alfio-event/alf.io/blob/master/src/main/java/alfio/controller/api/v1/AttendeeApiController.java#L80

let me know if you find anything suspicious, so that we can fix it :-)

Thanks!
Celestino

**Comment by ebartz** [comment]
As in my case this was a matter of testing it the wrong way, I think this can be closed.
